# Generated by Django 4.2.7 on 2025-07-06 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo4j_id', models.CharField(db_index=True, help_text='Corresponding Neo4j node ID', max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField(db_index=True, default=0)),
                ('parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Last sync with Neo4j')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TopicSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('single', 'Single Topic Sync')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_tags', to='topics.topic')),
            ],
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['level', 'title'], name='topics_topi_level_8b4acf_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['neo4j_id'], name='topics_topi_neo4j_i_e13c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active', 'level'], name='topics_topi_is_acti_99e396_idx'),
        ),
        migrations.AddIndex(
            model_name='topictag',
            index=models.Index(fields=['tag'], name='topics_topi_tag_8fda35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topictag',
            unique_together={('topic', 'tag')},
        ),
    ]
